### ISSUE TITLE
Is this for Unity or Visual Studio?

### ISSUE THREAD

**Issue by ghost** [jourdonnais/platformerGame#2]
Hey, I'm trying to run this platformer, is this for Unity? Or do I need to run it with Visual Studio. If it is with Visual Studio, could you please tell what the startup item is? Because i can't find it right now.

**Comment by csanadszilagyi** [comment]
Hi, honestly this is a very old project of mine, i have not updated it for a very long time. I also added other little stuffs since then, but i haven't commited yet.
As you can see in the readme file my experimental project was not developed in/for Unity. Altough it was built with C#, for visual things (windowing, handling input events, displaying things on the screen...etc) i used SFML.NET (check readme). Unfortunately i did not provide the asset files (sprites, sounds)...maybe i should update this project to provide a demo example, sorry for that. My very first idea was just to give some source code which can be used by anyone, who interested in game development as an inspiration for little game projects. It's basically just a simple Windows application, so when you compile it generates a runnable exe file. You can read more about [SFML](https://www.sfml-dev.org/) and [SFML.NET](https://www.sfml-dev.org/download/sfml.net/).

**Comment by ghost** [comment]
Thanks for the information, I actually downloaded this to play it lol. It would indeed be really nice if you could update it so there are some sprites.
